config/routes.rb
Casting::Application.routes.draw do
  
   root :to => "home#homepage"
  
  match '/about', :to => 'home#about'
  
  match '/termsofuse', :to => 'home#termsofuse'

  get "home/about"

  get "home/users"

  get "home/posts"

  get "home/news"

end

app/controllers/home_controller.rb
class HomeController < ApplicationController


  def termsofuse
    @title = "Termini di servizio"  
  end
  
  def home
    
  end
  
  def contact
    @title = "Contact us"
  end
  
  def about
    @title = "About"
  end

  def news
    
  end

  def users
  end

  def posts
  end
  
  def homepage
    
  end

  
 
end

app/helpers/application_helper.rb
module ApplicationHelper
  
  #return un nome diverso per ogni pagina
  
  def title
    base_title = "La Gilda"
    if @title.nil?
      base_title
    else
      "#{base_title} | #{@title}"
    end
  end
end

app/views/home/about.html.erb
<!DOCTYPE html>
<!-- Website template by freewebsitetemplates.com -->
<html>
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<title>La Gilda</title>
	<link rel="stylesheet" href="css/style.css" type="text/css" charset="utf-8" />	
</head>

<body>
	
		
		
			<span class="header"></span>
			<h3>About Us</h3>
			<div class="links">
				<a href="about.html">Share</a>
				<a href="http://twitter.com/fwtemplates" target="_blank" >Re-Tweet</a>
			</div>

			<div class="about">
				<span>Ecco cos'è la Gilda</span>
				<p>
					La Gilda è una community di maestri d'arte che hanno deciso volontariamente di insegnare e nel contempo imparare
					nel rispetto del concetto di Arte assoluto. Leggi i nostri <%= link_to "Termini di Servizio", termsofuse_path, :target => '_blank' %>.
				</p>

				<span>Cosa significa insegnare e imparare?</span>
				<p>
					Significa che i nostri maestri assolutamente qualificati e selezionati mettono a disposizione un certo numero
					di ore di lezione mensili che non prevedono un pagamento in denaro ma vengono ricambiate con un equivalente
					numero di ore di una lezione da loro prescelta!!
				</p>

				<span>E se non sono più disponibili ore?</span>
				<p> 
					Se il numero di ore è esaurito o se non potete "contraccambiare l'insegnamento" richiesto allora è previsto un compenso in denaro
					ben visibile nella pagina del maestro selezionato, ma attenzione!! Sempre nel rispetto di chi vuole imparare, se prenoti più
					lezioni mensilmente dai maestri della Gilda hai uno sconto sulla lezione, più ne prenoti, più aumenta lo sconto!!!</p>

				<span>E se volessi far parte della Gilda?</span>
				<p>
					 Se ti senti qualificato ad insegnare anche tu all'altezza dei maestri della Gilda riempi il Contact Form a piè pagina e verrai ricontattato
					 dai nostri selettori!!!
				</p>
			</div>
			

		
			<a href="homepage.html">Back to homepage>></a>
		
	
</body>
</html>

app/views/home/homepage.html.erb
<!DOCTYPE html>
<!-- Website template by freewebsitetemplates.com -->
<html>
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<title>La Gilda</title>
	<link rel="stylesheet" href="css/style.css" type="text/css" charset="utf-8" />	
</head>

<body>
	
		
		
	
			
			
		
			<span class="header"></span>
			<h3>Galleria</h3>
			<ul class="images">
				

				<li><img src="assets/images/lilla costarelli.jpg" alt="Img" /></li>
				<li><img src="assets/images/dario conti.jpg" alt="Img" /></li>
				<li><img src="assets/images/fabio dulzetto.jpg" alt="Img" /></li>
				<li><img src="assets/images/erika spagnolo.jpg" alt="Img" /></li>

				<li><img src="assets/images/enrico sortino.jpg" alt="Img" /></li>
				<li><img src="assets/images/phil gorman.jpg" alt="Img" /></li>
				<li><img src="assets/images/gianni nicotra.jpg" alt="Img" /></li>
				<li><img src="assets/images/giuseppe carbone.jpg" alt="Img" /></li>

				<li><img src="assets/images/patricia nugent.jpg" alt="Img" /></li>
				<li><img src="assets/images/jessica hauf.jpg" alt="Img" /></li>
				<li><img src="assets/images/manuela partanni.jpg" alt="Img" /></li>
				<li><img src="assets/images/marco ravalli.jpg" alt="Img" /></li>

				<li><img src="assets/images/melina manuli.jpg" alt="Img" /></li>
				<li><img src="assets/images/giovanni anzalone.jpg" alt="Img" /></li>
				<li><img src="assets/images/marco amato.jpg" alt="Img" /></li>
				<li><img src="assets/images/skye cameron.jpg" alt="Img" /></li>

				<li><img src="assets/images/giovanna dangi.jpg" alt="Img" /></li>
				<li><img src="assets/images/mariella argiracopulos.jpg" alt="Img" /></li>
				<li><img src="assets/images/dolly diaz.jpg" alt="Img" /></li>
				<li><img src="assets/images/francy ferro.jpg" alt="Img" /></li>

				
			</ul>
			
		<!-- /#contents -->

</body>
</html>

app/views/home/news.html.erb
<!DOCTYPE html>
<!-- Website template by freewebsitetemplates.com -->
<html>
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<title>La Gilda</title>
	<link rel="stylesheet" href="css/style.css" type="text/css" charset="utf-8" />	
</head>

<body>
	
		
		<div id="contents">
			<span class="header"></span>
			<h3>News</h3>
			<div class="links">
				<a href="about.html">Share</a>
				<a href="http://twitter.com/fwtemplates" target="_blank" >Re-Tweet</a>
			</div>

			<div class="about">
				<span>Queste sono le news</span>
				<p>
					Our website templates are created with inspiration, checked for quality and originality and meticulously sliced and coded. What&acute;s more, they&acute;re
					absolutely free! You can do a lot with them. You can modify them. You can use them to design websites for clients, so long as you agree with
					the <a href="http://www.freewebsitetemplates.com/about/termsofuse/">Terms of Use</a>. You can even remove all our links if you want to.
				</p>

				<span>We Have More Templates for You</span>
				<p>
					Looking for more templates? Just browse through all our <a href="http://www.freewebsitetemplates.com/">Free Website	Templates</a> and find what you&acute;re looking for. But if you don&acute;t find any
					website template you can use, you can try our <a href="http://www.freewebsitetemplates.com/freewebdesign/">Free Web Design</a> service and tell us all about it. Maybe you&acute;re looking for something different,
					something special. And we love the challenge of doing something	different and something special.
				</p>

				<span>Be Part of Our Community</span>
				<p>If you&acute;re experiencing issues and concerns about this website template, join the discussion <a href="http://www.freewebsitetemplates.com/forum/">on our forum</a> and meet other people in the community who share the same interests with you.</p>

				<span>Template details</span>
				<p>
					Version 3<br/>
					Website Template details, discussion and updates for this <a href="http://www.freewebsitetemplates.com/forum/f18/artist-website-template-18576">Artist Website Template</a>.
					Website Template design by <a href="http://www.freewebsitetemplates.com/">Free Website Templates</a>.
					Please feel free to remove some or all the text and links of this page and replace it with your own About content.
				</p>
			</div>

			<div class="tags">
				<span>Tags:</span>
				<a href="#">Tag numbers</a>
				<a href="#">local</a>
				<a href="#">jeopardy</a>
				<a href="#">star wars</a>
				<a href="#">example</a>
			</div>

			<ul class="images">
				<li><img src="images/sexy-girl.jpg" alt="Img" /></li>
				<li><img src="images/girl-smiling3.jpg" alt="Img" /></li>
				<li><img src="images/long-bland-hair.jpg" alt="Img" /></li>
				<li><img src="images/girl-smiling4.jpg" alt="Img" /></li>

				<li><img src="images/family.jpg" alt="Img" /></li>
				<li><img src="images/shock.jpg" alt="Img" /></li>
				<li><img src="images/boy-with-headphones.jpg" alt="Img" /></li>
				<li><img src="images/fat-girl.jpg" alt="Img" /></li>
			</ul>
			<a href="index.html" class="img-gallery">Back to gallery of images >></a>
		</div> <!-- /#contents -->
	</div> <!-- /#page -->
</body>
</html>

app/views/home/posts.html.erb
<h1>Home#posts</h1>
<p>Find me in app/views/home/posts.html.erb</p>

app/views/home/termsofuse.html.erb
<!DOCTYPE html>
<!-- Website template by freewebsitetemplates.com -->
<html>
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<title>La Gilda</title>
	<link rel="stylesheet" href="css/style.css" type="text/css" charset="utf-8" />	
</head>	
	<body>
		
				<div class="terms">
<h2>
	Web Site Terms and Conditions of Use
</h2>

<h3>
	1. Terms
</h3>

<p>
	By accessing this web site, you are agreeing to be bound by these 
	web site Terms and Conditions of Use, all applicable laws and regulations, 
	and agree that you are responsible for compliance with any applicable local 
	laws. If you do not agree with any of these terms, you are prohibited from 
	using or accessing this site. The materials contained in this web site are 
	protected by applicable copyright and trade mark law.
</p>

<h3>
	2. Use License
</h3>

<ol type="a">
	<li>
		Permission is granted to temporarily download one copy of the materials 
		(information or software) on La Gilda's web site for personal, 
		non-commercial transitory viewing only. This is the grant of a license, 
		not a transfer of title, and under this license you may not:
		
		<ol type="i">
			<li>modify or copy the materials;</li>
			<li>use the materials for any commercial purpose, or for any public display (commercial or non-commercial);</li>
			<li>attempt to decompile or reverse engineer any software contained on La Gilda's web site;</li>
			<li>remove any copyright or other proprietary notations from the materials; or</li>
			<li>transfer the materials to another person or "mirror" the materials on any other server.</li>
		</ol>
	</li>
	<li>
		This license shall automatically terminate if you violate any of these restrictions and may be terminated by La Gilda at any time. Upon terminating your viewing of these materials or upon the termination of this license, you must destroy any downloaded materials in your possession whether in electronic or printed format.
	</li>
</ol>

<h3>
	3. Disclaimer
</h3>

<ol type="a">
	<li>
		The materials on La Gilda's web site are provided "as is". La Gilda makes no warranties, expressed or implied, and hereby disclaims and negates all other warranties, including without limitation, implied warranties or conditions of merchantability, fitness for a particular purpose, or non-infringement of intellectual property or other violation of rights. Further, La Gilda does not warrant or make any representations concerning the accuracy, likely results, or reliability of the use of the materials on its Internet web site or otherwise relating to such materials or on any sites linked to this site.
	</li>
</ol>

<h3>
	4. Limitations
</h3>

<p>
	In no event shall La Gilda or its suppliers be liable for any damages (including, without limitation, damages for loss of data or profit, or due to business interruption,) arising out of the use or inability to use the materials on La Gilda's Internet site, even if La Gilda or a La Gilda authorized representative has been notified orally or in writing of the possibility of such damage. Because some jurisdictions do not allow limitations on implied warranties, or limitations of liability for consequential or incidental damages, these limitations may not apply to you.
</p>
			
<h3>
	5. Revisions and Errata
</h3>

<p>
	The materials appearing on La Gilda's web site could include technical, typographical, or photographic errors. La Gilda does not warrant that any of the materials on its web site are accurate, complete, or current. La Gilda may make changes to the materials contained on its web site at any time without notice. La Gilda does not, however, make any commitment to update the materials.
</p>

<h3>
	6. Links
</h3>

<p>
	La Gilda has not reviewed all of the sites linked to its Internet web site and is not responsible for the contents of any such linked site. The inclusion of any link does not imply endorsement by La Gilda of the site. Use of any such linked web site is at the user's own risk.
</p>

<h3>
	7. Site Terms of Use Modifications
</h3>

<p>
	La Gilda may revise these terms of use for its web site at any time without notice. By using this web site you are agreeing to be bound by the then current version of these Terms and Conditions of Use.
</p>

<h3>
	8. Governing Law
</h3>

<p>
	Any claim relating to La Gilda's web site shall be governed by the laws of the State of Italy without regard to its conflict of law provisions.
</p>

<p>
	General Terms and Conditions applicable to Use of a Web Site.
</p>



<h2>
	Privacy Policy
</h2>

<p>
	Your privacy is very important to us. Accordingly, we have developed this Policy in order for you to understand how we collect, use, communicate and disclose and make use of personal information. The following outlines our privacy policy.
</p>


	<li>
		Before or at the time of collecting personal information, we will identify the purposes for which information is being collected.
	</li>
	<li>
		We will collect and use of personal information solely with the objective of fulfilling those purposes specified by us and for other compatible purposes, unless we obtain the consent of the individual concerned or as required by law.		
	</li>
	<li>
		We will only retain personal information as long as necessary for the fulfillment of those purposes. 
	</li>
	<li>
		We will collect personal information by lawful and fair means and, where appropriate, with the knowledge or consent of the individual concerned. 
	</li>
	<li>
		Personal data should be relevant to the purposes for which it is to be used, and, to the extent necessary for those purposes, should be accurate, complete, and up-to-date. 
	</li>
	<li>
		We will protect personal information by reasonable security safeguards against loss or theft, as well as unauthorized access, disclosure, copying, use or modification.
	</li>
	<li>
		We will make readily available to customers information about our policies and practices relating to the management of personal information. 
	</li>


<p>
	We are committed to conducting our business in accordance with these principles in order to ensure that the confidentiality of personal information is protected and maintained. 
</p>		
</div>

</body>
</html>			

app/views/home/users.html.erb
<h1>Home#users</h1>
<p>Find me in app/views/home/users.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<!-- Website template by freewebsitetemplates.com -->
<html>
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<title> <%= title %> </title>
	<link rel="stylesheet" href="css/style.css" type="text/css" charset="utf-8" />	
  <%= stylesheet_link_tag 'blueprint/screen', :media => 'screen' %>
  <%= stylesheet_link_tag 'blueprint/print', :media => 'print' %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
  <!-- [if -lt IE 9]>
  	<script src= "http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
  <![endif]-->
  <!-- [if -lt IE 9]>
  	<%= stylesheet_link_tag 'blueprint/ie' %>
  <![endif]-->
  <%= stylesheet_link_tag 'prova', :media => 'screen' %>

</head>

<body>
		

	<div id="background"></div>
	<div id="page">
		<div id="sidebar">
			<div id="logo">
				<%= link_to image_tag("I selezionati maestri d'arte\n disponibili per te"), root_path %>
					
			</div> <!-- /#logo -->
			<ul id="navigation">
				<li><%= link_to "About us", about_path %></a></li>
				<li><%= link_to "Galleria", root_path %></a></li>
				<li><a href="images.html">Iscriviti adesso</a></li>
				<li><a href="contact-us.html">Scegli la tua lezione</a></li>
				<li><a href="blog.html">Forum</a></li>
			</ul> <!-- /#navigation -->
			<ul id="connect">
				<li><a href="http://facebook.com/freewebsitetemplates" target="_blank" class="facebook"></a></li>
				<li><a href="http://twitter.com/fwtemplates" target="_blank" class="twitter"></a></li>
				<li><a href="" class="link-us"></a></li>
			</ul> <!-- /#connect -->
			<div class="footer">
				&copy; Copyright &copy; 2012.<br/>
				<a href="http://www.facebook.com/?action=read&tid=id.253765924714446&sk=inbox&page&query#!/profile.php?id=1575332772">Axel Vee</a> all rights reserved.
			
			
		</div> <!-- /.footer -->
			
		
			
		</div> <!-- /#sidebar -->
		
	

	<div id="contents">
			<section class="corpo">
		<%=  yield %>
			</section>


	<div class="tags">
				 
					<a> <%= link_to "Contact", "#" %> </a>
					<a> <%= link_to "News", "#" %> </a>
				
				</div>
				</div>
	</div> <!-- /#page -->


</body>
		

</html>